# Generated by Django 5.1.6 on 2026-06-27 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_verificationrequest_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('uploaded_file', 'Uploaded file'), ('provider_export', 'Provider export'), ('profile_snapshot', 'Profile snapshot'), ('service_listing_snapshot', 'Service listing snapshot'), ('url', 'URL'), ('manual_text', 'Manual text')], default='uploaded_file', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('visibility', models.CharField(choices=[('public_marketplace', 'Public marketplace'), ('customer_after_contact', 'Customer after contact'), ('customer_after_order', 'Customer after order'), ('provider_private', 'Provider private'), ('admin_only', 'Admin only')], default='provider_private', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_processing', 'Pending processing'), ('active', 'Active'), ('archived', 'Archived'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending_processing', max_length=30)),
                ('language', models.CharField(blank=True, max_length=12)),
                ('source_version', models.PositiveIntegerField(default=1)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_sources', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='providers.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('full_ingestion', 'Full ingestion'), ('extract', 'Extract'), ('chunk', 'Chunk'), ('embed', 'Embed'), ('reindex', 'Reindex')], default='full_ingestion', max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='knowledge.knowledgesource')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('raw_text_storage_path', models.CharField(blank=True, max_length=500)),
                ('normalized_text_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('detected_language', models.CharField(blank=True, max_length=12)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('extractor_version', models.CharField(default='v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='providers.providerprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgesource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('chunk_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, max_length=120)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=12)),
                ('visibility', models.CharField(max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='providers.providerprofile')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgesource')),
            ],
            options={
                'ordering': ['source_id', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['provider', 'visibility', 'status'], name='knowledge_k_provide_67721e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['checksum_sha256'], name='knowledge_k_checksu_6f7233_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestionjob',
            index=models.Index(fields=['status', 'job_type', 'created_at'], name='knowledge_k_status_d7403f_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestionjob',
            index=models.Index(fields=['source', 'status'], name='knowledge_k_source__08517b_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['source', 'extraction_status'], name='knowledge_k_source__d1a668_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['provider', 'extraction_status'], name='knowledge_k_provide_c2e9be_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['provider', 'visibility', 'is_active'], name='knowledge_k_provide_156841_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['source', 'is_active'], name='knowledge_k_source__a6aead_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['chunk_hash'], name='knowledge_k_chunk_h_970f38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgechunk',
            unique_together={('source', 'chunk_index', 'chunk_hash')},
        ),
    ]
