# Generated by Django 5.1.6 on 2026-06-27 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        ('orders', '0001_initial'),
        ('providers', '0002_verificationrequest_details'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_sessions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_sessions', to='orders.order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_sessions', to='providers.providerprofile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_sessions', to='services.servicelisting')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('normalized_question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('answer_status', models.CharField(choices=[('answered', 'Answered'), ('insufficient_evidence', 'Insufficient evidence'), ('blocked_by_policy', 'Blocked by policy'), ('error', 'Error')], max_length=30)),
                ('customer_next_step', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('embedding_model', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(default='customer-rag-v1', max_length=40)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_turns', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_turns', to='providers.providerprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='customer_assistant.assistantsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('relevance_score', models.FloatField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_citations', to='knowledge.knowledgechunk')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_citations', to='providers.providerprofile')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_citations', to='knowledge.knowledgesource')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='customer_assistant.assistantturn')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='assistantsession',
            index=models.Index(fields=['customer', 'provider', 'status'], name='customer_as_custome_a0f7c7_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantsession',
            index=models.Index(fields=['provider', 'status'], name='customer_as_provide_732306_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantturn',
            index=models.Index(fields=['session', 'created_at'], name='customer_as_session_1df9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantturn',
            index=models.Index(fields=['customer', 'created_at'], name='customer_as_custome_d7306a_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantturn',
            index=models.Index(fields=['provider', 'answer_status'], name='customer_as_provide_a5f69d_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantcitation',
            index=models.Index(fields=['turn', 'rank'], name='customer_as_turn_id_2a4722_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantcitation',
            index=models.Index(fields=['provider', 'created_at'], name='customer_as_provide_047c44_idx'),
        ),
    ]
