class RecommendationTaxonomy:
    ANALYSIS_KEYS = (
        "service_category",
        "provider_type",
        "likely_issue",
        "urgency",
        "keywords",
        "suggested_solution",
        "quick_tips",
    )
    SUPPORTED_SERVICE_CATEGORIES = {
        "plumbing",
        "electrical",
        "cleaning",
        "painting",
        "landscaping",
        "moving",
        "carpentry",
        "air_conditioning",
    }
    SUPPORTED_PROVIDER_TYPES = {
        "plumber",
        "electrician",
        "cleaner",
        "painter",
        "landscaper",
        "mover",
        "carpenter",
        "ac_technician",
    }
    SERVICE_CATEGORY_TO_PROVIDER_TYPE = {
        "plumbing": "plumber",
        "electrical": "electrician",
        "cleaning": "cleaner",
        "painting": "painter",
        "landscaping": "landscaper",
        "moving": "mover",
        "carpentry": "carpenter",
        "air_conditioning": "ac_technician",
    }
    PROVIDER_TYPE_TO_SERVICE_CATEGORY = {
        "plumber": "plumbing",
        "electrician": "electrical",
        "cleaner": "cleaning",
        "painter": "painting",
        "landscaper": "landscaping",
        "mover": "moving",
        "carpenter": "carpentry",
        "ac_technician": "air_conditioning",
    }
    SERVICE_CATEGORY_HINTS = {
        "plumbing": {
            "leak",
            "leaking",
            "water",
            "pipe",
            "pipes",
            "sink",
            "faucet",
            "drain",
            "toilet",
            "shower",
            "tap",
            "under sink",
            "تسريب",
            "تسرب",
            "ماء",
            "ماسورة",
            "مواسير",
            "انبوب",
            "أنبوب",
            "مغسلة",
            "حنفية",
            "صنبور",
            "بالوعة",
            "صرف",
            "مرحاض",
            "دش",
        },
        "electrical": {
            "power",
            "electricity",
            "electrical",
            "socket",
            "outlet",
            "switch",
            "panel",
            "breaker",
            "wire",
            "wiring",
            "light",
            "lights",
            "buzzing",
            "كهرباء",
            "كهربائي",
            "مقبس",
            "فيش",
            "مفتاح",
            "لوحة",
            "قاطع",
            "سلك",
            "اسلاك",
            "أسلاك",
            "لمبة",
            "إضاءة",
            "اضاءة",
        },
        "cleaning": {
            "clean",
            "cleaning",
            "dirty",
            "dirt",
            "stain",
            "stains",
            "dust",
            "deep clean",
            "mess",
            "تنظيف",
            "نظافة",
            "نظافه",
            "وسخ",
            "بقعة",
            "بقع",
            "غبار",
            "تعزيل",
        },
        "painting": {
            "paint",
            "painting",
            "repaint",
            "wall",
            "walls",
            "ceiling",
            "color",
            "دهان",
            "دهانات",
            "صباغ",
            "طلاء",
            "حائط",
            "جدار",
            "سقف",
        },
        "landscaping": {
            "garden",
            "yard",
            "lawn",
            "grass",
            "tree",
            "plants",
            "irrigation",
            "backyard",
            "حديقة",
            "حديقه",
            "حدائق",
            "حدايق",
            "عشب",
            "شجر",
            "زرع",
            "ري",
        },
        "moving": {
            "move",
            "moving",
            "relocation",
            "furniture",
            "boxes",
            "pack",
            "packing",
            "office move",
            "نقل",
            "ترحيل",
            "اثاث",
            "أثاث",
            "صناديق",
            "تحميل",
        },
        "carpentry": {
            "wood",
            "wooden",
            "door",
            "cabinet",
            "drawer",
            "shelf",
            "table",
            "chair",
            "furniture repair",
            "نجارة",
            "نجاره",
            "نجار",
            "خشب",
            "باب",
            "خزانة",
            "خزانه",
            "درج",
            "رف",
            "طاولة",
            "طاوله",
            "كرسي",
        },
        "air_conditioning": {
            "ac",
            "a c",
            "a/c",
            "air conditioner",
            "air conditioning",
            "hvac",
            "cooling",
            "cool",
            "not cooling",
            "temperature",
            "refrigerant",
            "compressor",
            "مكيف",
            "مكيفات",
            "تكييف",
            "التكييف",
            "تبريد",
            "لا يبرد",
            "مو بارد",
            "حرارة",
            "فريون",
            "كمبروسر",
        },
    }
    SERVICE_CATEGORY_ALIASES = {
        "plumbing": {
            "plumbing",
            "plumbing service",
            "plumbing services",
            "pipe repair",
            "water leak",
            "سباكة",
            "سباكه",
            "السباكة",
            "السباكه",
            "تمديدات صحية",
            "تمديدات صحيه",
            "صحي",
            "فني صحي",
            "سباك",
        },
        "electrical": {
            "electrical",
            "electric",
            "electrician",
            "electrical service",
            "electrical services",
            "كهرباء",
            "الكهرباء",
            "كهربائي",
            "فني كهرباء",
            "صيانة كهرباء",
            "صيانه كهرباء",
        },
        "cleaning": {
            "cleaning",
            "cleaner",
            "house cleaning",
            "deep cleaning",
            "janitorial",
            "تنظيف",
            "التنظيف",
            "عامل نظافة",
            "عامل نظافه",
            "شركة تنظيف",
            "خدمة تنظيف",
            "خدمات تنظيف",
        },
        "painting": {
            "painting",
            "painter",
            "paint",
            "painting service",
            "دهان",
            "دهانات",
            "صباغ",
            "طلاء",
            "دهن",
        },
        "landscaping": {
            "landscaping",
            "landscape",
            "landscaper",
            "gardening",
            "garden",
            "تنسيق حدائق",
            "تنسيق حدايق",
            "حدائق",
            "حدايق",
            "بستنة",
            "بستاني",
            "حديقة",
            "حديقه",
        },
        "moving": {
            "moving",
            "mover",
            "relocation",
            "moving service",
            "moving company",
            "نقل",
            "نقل اثاث",
            "نقل أثاث",
            "شركة نقل",
            "عمال نقل",
            "ترحيل",
        },
        "carpentry": {
            "carpentry",
            "carpenter",
            "woodwork",
            "نجارة",
            "نجاره",
            "نجار",
            "اعمال خشب",
            "أعمال خشب",
            "خشب",
        },
        "air_conditioning": {
            "air conditioning",
            "air_conditioning",
            "ac",
            "a c",
            "a/c",
            "hvac",
            "cooling",
            "air conditioner",
            "ac repair",
            "hvac repair",
            "تكييف",
            "التكييف",
            "مكيف",
            "مكيفات",
            "صيانة مكيفات",
            "صيانه مكيفات",
            "تبريد",
            "تكييف وتبريد",
            "مكيف هواء",
        },
    }
    PROVIDER_TYPE_ALIASES = {
        "plumber": {
            "plumber",
            "plumbing technician",
            "plumbing specialist",
            "سباك",
            "فني سباكة",
            "فني سباكه",
            "فني صحي",
            "عامل صحي",
        },
        "electrician": {
            "electrician",
            "electrical technician",
            "electrical specialist",
            "كهربائي",
            "فني كهرباء",
            "مختص كهرباء",
        },
        "cleaner": {
            "cleaner",
            "cleaning service",
            "cleaning crew",
            "house cleaner",
            "عامل نظافة",
            "عامل نظافه",
            "شركة تنظيف",
            "فريق تنظيف",
        },
        "painter": {
            "painter",
            "painting contractor",
            "دهان",
            "صباغ",
            "فني دهان",
            "فني طلاء",
        },
        "landscaper": {
            "landscaper",
            "gardener",
            "garden specialist",
            "منسق حدائق",
            "منسق حدايق",
            "بستاني",
            "فني حدائق",
        },
        "mover": {
            "mover",
            "moving company",
            "moving crew",
            "عمال نقل",
            "ناقل اثاث",
            "ناقل أثاث",
            "شركة نقل",
            "مختص نقل",
        },
        "carpenter": {
            "carpenter",
            "woodworker",
            "نجار",
            "فني نجارة",
            "فني نجاره",
            "عامل خشب",
        },
        "ac_technician": {
            "ac technician",
            "air conditioning technician",
            "hvac technician",
            "cooling technician",
            "ac specialist",
            "فني تكييف",
            "فني مكيفات",
            "فني تبريد",
            "فني تكييف وتبريد",
            "مختص تكييف",
            "مصلح مكيف",
        },
    }
    URGENCY_ALIASES = {
        "high": {
            "high",
            "urgent",
            "emergency",
            "asap",
            "immediate",
            "critical",
            "right away",
            "عاجل",
            "طارئ",
            "طاري",
            "فوري",
            "فورا",
            "فوراً",
            "حالاً",
            "حالا",
            "باسرع وقت",
            "بأسرع وقت",
            "ضروري",
            "خطير",
            "مرتفعة",
            "مرتفع",
        },
        "medium": {
            "medium",
            "moderate",
            "normal",
            "soon",
            "standard",
            "متوسط",
            "متوسطة",
            "عادي",
            "عادية",
            "قريبا",
            "قريباً",
            "خلال اليوم",
            "اليوم",
        },
        "low": {
            "low",
            "minor",
            "routine",
            "whenever",
            "not urgent",
            "flexible",
            "منخفض",
            "منخفضة",
            "بسيط",
            "بسيطة",
            "غير عاجل",
            "غير مستعجل",
        },
    }
    HIGH_URGENCY_TOKENS = (
        "urgent",
        "emergency",
        "asap",
        "immediate",
        "right away",
        "عاجل",
        "طارئ",
        "فوري",
        "ضروري",
        "باسرع وقت",
        "بأسرع وقت",
    )
    LOW_URGENCY_TOKENS = (
        "not urgent",
        "routine",
        "whenever",
        "غير عاجل",
        "بسيط",
        "منخفض",
    )
    ARABIC_CHAR_TRANSLATIONS = str.maketrans(
        {
            "أ": "ا",
            "إ": "ا",
            "آ": "ا",
            "ٱ": "ا",
            "ؤ": "و",
            "ئ": "ي",
            "ى": "ي",
        }
    )

    @classmethod
    def provider_type_for_category(cls, service_category: str) -> str:
        return cls.SERVICE_CATEGORY_TO_PROVIDER_TYPE.get(service_category, "")

    @classmethod
    def service_category_for_provider_type(cls, provider_type: str) -> str:
        return cls.PROVIDER_TYPE_TO_SERVICE_CATEGORY.get(provider_type, "")
